# Generated by Django 4.2.21 on 2025-09-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0097_meeting_meetingattachment_meetingagenda_issue_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('live', 'Live'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='Meeting Status'),
        ),
    ]
