# Generated by Django 4.2.21 on 2025-11-16 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0098_alter_meeting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganogramPosition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Position Name')),
                ('authority', models.CharField(choices=[('none', 'None'), ('head', 'Head'), ('line_manager', 'Line Manager')], default='none', max_length=20, verbose_name='Authority Level')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.organogramposition')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organogram_positions', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Organogram Position',
                'verbose_name_plural': 'Organogram Positions',
                'db_table': 'organogram_positions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceOrganogram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Organogram Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('positions', models.ManyToManyField(blank=True, related_name='organograms', to='db.organogramposition')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organograms', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Organogram',
                'verbose_name_plural': 'Workspace Organograms',
                'db_table': 'workspace_organograms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='db.organogramposition')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Position',
                'verbose_name_plural': 'User Positions',
                'db_table': 'user_positions',
                'ordering': ('-assigned_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='workspaceorganogram',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace'), name='workspace_organogram_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceorganogram',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='userposition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'position'), name='user_position_unique_user_position_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='userposition',
            unique_together={('user', 'position', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='organogramposition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace'), name='organogram_position_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='organogramposition',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
    ]
